//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Origami.Identity.Api.Core.Data {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DataObjects {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataObjects() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Origami.Identity.Api.Core.Data.DataObjects", typeof(DataObjects).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[Usp_Catalogs_Users].
        /// </summary>
        internal static string Usp_Catalogs_Users {
            get {
                return ResourceManager.GetString("Usp_Catalogs_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[Usp_ReplicateAccessibilityNetUsers].
        /// </summary>
        internal static string Usp_ReplicateAccessibilityNetUsers {
            get {
                return ResourceManager.GetString("Usp_ReplicateAccessibilityNetUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[Usp_ReplicateAspNetRoles].
        /// </summary>
        internal static string Usp_ReplicateAspNetRoles {
            get {
                return ResourceManager.GetString("Usp_ReplicateAspNetRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[Usp_ReplicateAspNetUserRoles].
        /// </summary>
        internal static string Usp_ReplicateAspNetUserRoles {
            get {
                return ResourceManager.GetString("Usp_ReplicateAspNetUserRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[Usp_ReplicateUsers].
        /// </summary>
        internal static string Usp_ReplicateUsers {
            get {
                return ResourceManager.GetString("Usp_ReplicateUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[Usp_Security_Accessibility_GET].
        /// </summary>
        internal static string Usp_Security_Accessibility_GET {
            get {
                return ResourceManager.GetString("Usp_Security_Accessibility_GET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[Usp_Security_AccessibilityNetUsers_INS].
        /// </summary>
        internal static string Usp_Security_AccessibilityNetUsers_INS {
            get {
                return ResourceManager.GetString("Usp_Security_AccessibilityNetUsers_INS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[Usp_Security_AccessibilityNetUsers_Upd].
        /// </summary>
        internal static string Usp_Security_AccessibilityNetUsers_Upd {
            get {
                return ResourceManager.GetString("Usp_Security_AccessibilityNetUsers_Upd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[Usp_Security_Components_By_User_Get].
        /// </summary>
        internal static string Usp_Security_Components_By_User_Get {
            get {
                return ResourceManager.GetString("Usp_Security_Components_By_User_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[Usp_Security_Components_Get].
        /// </summary>
        internal static string Usp_Security_Components_Get {
            get {
                return ResourceManager.GetString("Usp_Security_Components_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[Usp_security_GetModuleNew].
        /// </summary>
        internal static string Usp_security_GetModuleNew {
            get {
                return ResourceManager.GetString("Usp_security_GetModuleNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[Usp_Security_Module_Get].
        /// </summary>
        internal static string Usp_Security_Module_Get {
            get {
                return ResourceManager.GetString("Usp_Security_Module_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[Usp_Security_ModulePermisson_Get].
        /// </summary>
        internal static string Usp_Security_ModulePermisson_Get {
            get {
                return ResourceManager.GetString("Usp_Security_ModulePermisson_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[Usp_Security_Modules_GET].
        /// </summary>
        internal static string Usp_Security_Modules_GET {
            get {
                return ResourceManager.GetString("Usp_Security_Modules_GET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[Usp_Security_Modulo_GET].
        /// </summary>
        internal static string Usp_Security_Modulo_GET {
            get {
                return ResourceManager.GetString("Usp_Security_Modulo_GET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[Usp_Security_PermissonINS].
        /// </summary>
        internal static string Usp_Security_PermissonINS {
            get {
                return ResourceManager.GetString("Usp_Security_PermissonINS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[Usp_Security_PermissonRoles_DEL].
        /// </summary>
        internal static string Usp_Security_PermissonRoles_DEL {
            get {
                return ResourceManager.GetString("Usp_Security_PermissonRoles_DEL", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[Usp_Security_PermissonRoles_GETL].
        /// </summary>
        internal static string Usp_Security_PermissonRoles_GETL {
            get {
                return ResourceManager.GetString("Usp_Security_PermissonRoles_GETL", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[Usp_Security_Permissons].
        /// </summary>
        internal static string Usp_Security_Permissons {
            get {
                return ResourceManager.GetString("Usp_Security_Permissons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[Usp_Security_PermissonSpecial_Del].
        /// </summary>
        internal static string Usp_Security_PermissonSpecial_Del {
            get {
                return ResourceManager.GetString("Usp_Security_PermissonSpecial_Del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[Usp_Security_PermissonSpecial_Get].
        /// </summary>
        internal static string Usp_Security_PermissonSpecial_Get {
            get {
                return ResourceManager.GetString("Usp_Security_PermissonSpecial_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[Usp_Security_Position].
        /// </summary>
        internal static string Usp_Security_Position {
            get {
                return ResourceManager.GetString("Usp_Security_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[Usp_Security_RecoveryCodes_DEL].
        /// </summary>
        internal static string Usp_Security_RecoveryCodes_DEL {
            get {
                return ResourceManager.GetString("Usp_Security_RecoveryCodes_DEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[Usp_Security_RecoveryCodes_GET].
        /// </summary>
        internal static string Usp_Security_RecoveryCodes_GET {
            get {
                return ResourceManager.GetString("Usp_Security_RecoveryCodes_GET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[Usp_Security_RecoveryCodes_INS].
        /// </summary>
        internal static string Usp_Security_RecoveryCodes_INS {
            get {
                return ResourceManager.GetString("Usp_Security_RecoveryCodes_INS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[Usp_Security_Replicate_Users].
        /// </summary>
        internal static string Usp_Security_Replicate_Users {
            get {
                return ResourceManager.GetString("Usp_Security_Replicate_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[Usp_Security_Rol_Get].
        /// </summary>
        internal static string Usp_Security_Rol_Get {
            get {
                return ResourceManager.GetString("Usp_Security_Rol_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[Usp_Security_Rol_UDP].
        /// </summary>
        internal static string Usp_Security_Rol_UDP {
            get {
                return ResourceManager.GetString("Usp_Security_Rol_UDP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[Usp_Security_Role_GETL].
        /// </summary>
        internal static string Usp_Security_Role_GETL {
            get {
                return ResourceManager.GetString("Usp_Security_Role_GETL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[Usp_Security_RoleByUserId_GET].
        /// </summary>
        internal static string Usp_Security_RoleByUserId_GET {
            get {
                return ResourceManager.GetString("Usp_Security_RoleByUserId_GET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[Usp_Security_RolesByUserId_GET].
        /// </summary>
        internal static string Usp_Security_RolesByUserId_GET {
            get {
                return ResourceManager.GetString("Usp_Security_RolesByUserId_GET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[Usp_Security_UpdateUserRols].
        /// </summary>
        internal static string Usp_Security_UpdateUserRols {
            get {
                return ResourceManager.GetString("Usp_Security_UpdateUserRols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[Usp_Security_Users_Access_Ins].
        /// </summary>
        internal static string Usp_Security_Users_Access_Ins {
            get {
                return ResourceManager.GetString("Usp_Security_Users_Access_Ins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[Usp_Security_Users_GET].
        /// </summary>
        internal static string Usp_Security_Users_GET {
            get {
                return ResourceManager.GetString("Usp_Security_Users_GET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[Usp_Security_Users_GETL].
        /// </summary>
        internal static string Usp_Security_Users_GETL {
            get {
                return ResourceManager.GetString("Usp_Security_Users_GETL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[Usp_SecurityPermissonPivot].
        /// </summary>
        internal static string Usp_SecurityPermissonPivot {
            get {
                return ResourceManager.GetString("Usp_SecurityPermissonPivot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[Usp_SecurityPermissonPivot2].
        /// </summary>
        internal static string Usp_SecurityPermissonPivot2 {
            get {
                return ResourceManager.GetString("Usp_SecurityPermissonPivot2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[Usp_Sinchronize_Catalogs_CBU].
        /// </summary>
        internal static string Usp_Sinchronize_Catalogs_CBU {
            get {
                return ResourceManager.GetString("Usp_Sinchronize_Catalogs_CBU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[Usp_Sinchronize_Catalogs_REGION].
        /// </summary>
        internal static string Usp_Sinchronize_Catalogs_REGION {
            get {
                return ResourceManager.GetString("Usp_Sinchronize_Catalogs_REGION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[Usp_Sinchronize_Catalogs_SITE].
        /// </summary>
        internal static string Usp_Sinchronize_Catalogs_SITE {
            get {
                return ResourceManager.GetString("Usp_Sinchronize_Catalogs_SITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[Usp_Sinchronize_Catalogs_SITEBYREGION].
        /// </summary>
        internal static string Usp_Sinchronize_Catalogs_SITEBYREGION {
            get {
                return ResourceManager.GetString("Usp_Sinchronize_Catalogs_SITEBYREGION", resourceCulture);
            }
        }
    }
}
